version: "3.9"

services:
  db:
    image: postgres:15.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - django
  app:
    image: python:3.10
    working_dir: /classroom
    command: bash -c "scripts/install_deps.sh && scripts/run_server.sh"
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - .:/classroom
    networks:
      - django

volumes:
  db:
    driver: local

networks:
  django:
    driver: bridge
