version: "3.9"

services:
  db:
    image: postgres:15.2
    restart: on-failure
    environment:
      - POSTGRES_DB=login
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
